[공통 컴포넌트] CircleImage 컴포넌트를 추가합니다
TheNewestWorld/groove-front pull request #15
Opened 2022-07-30 08:08 UTC by Ho2eny

### 요구 사항
- [x] [CircleImage 컴포넌트](https://www.notion.so/CircleImage-aa648818c7094d37ab2bc09c3ec15404)를 추가합니다
  
### 수정 내역

| Design | Storybook |
|-|-|
|![image](https://user-images.githubusercontent.com/50590025/181888819-ec7ba670-3fd9-4640-9063-3d4b1ed23f57.png)|![image](https://user-images.githubusercontent.com/50590025/181888955-10f69dbf-f2c4-46cd-b5c7-b4987a2c1134.png)|

이미지 크기는 같지만, 캡쳐로 인해서 사이즈가 많이 달라보입니다.. 😢

2022-08-12 13:50 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.scss
> +  }
[여기에](https://github.com/TheNewestWorld/groove-front/pull/15/files#diff-2efe8dacc570e3a8aae1fd3214788ce309cc44934deb6e6f1104ad7054986202R1-R9) 수정되었습니다

2022-08-12 13:51 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.tsx
https://github.com/TheNewestWorld/groove-front/pull/15/commits/8a15ed4e606384e3cbbcd3a64c6f9ecaa6002dd0 수정되었습니다

2022-08-12 13:51 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.tsx
> +interface props extends ImgHTMLAttributes<HTMLImageElement> {
https://github.com/TheNewestWorld/groove-front/pull/15/commits/8a15ed4e606384e3cbbcd3a64c6f9ecaa6002dd0 수정되었습니다

2022-08-13 09:30 UTC, wlsdhr0831 requested changes

2022-08-13 09:30 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.scss
> +img {
이렇게 element tag 명으로 속성을 넣으시면
전체 적용이 됩니다.
클래스 명으로 변경해주세요~
아니면 아래 예시 처럼 특정 클래스 안에 있는 요소에 한에서 적용되도록 제한을 두어야 할 것같아요~

`
.circle-image {
    & > img { 
        ...
    }
}
`

2022-08-13 09:30 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.stories.scss
> +}
일반적으로 stories 용 scss 는 작업하지 않습니다.
이렇게 따로 작업하게 될 경우 실제 구현되어 사용하는 컴포넌트와 스토리북에 보여지는 모양을
변경할때 마다 싱크 맞추기 작업을 진행해야 합니다.

그냥 기본 상태만 보여지게 진행해도 될듯합니다.

2022-08-13 09:30 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.stories.tsx
> +  classname: classnames(['small', 'fit-contain'])
그리고 실제 사용하는 경우 classname 값은 여러개로 나누어 작업하는 것이 아니라
Main.tsx 에서 CircleImage를 사용하되 사이즈를 변경하고 싶은 경우
classname을 `profile-image` 이렇게 하나만 넘겨 준 후
Main.scss 에서 아래의 코드처럼 한번에 정의해서 사용하는 것이 편합니다.
`
.profile-image {
    width: 100px;
    height: 100px;
    object-fit: cover;
}
`

2022-08-13 09:30 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.stories.tsx
>  const Template: ComponentStory<typeof CircleImage> = (args) => <CircleImage {...args} />;
스토리북에서 여러개의 컴포넌트의 경우를 보여주는 상황은
props에 정의된 값들만 변경하여특정 상황들에 한해서 다양한 모습을 보여주는 경우입니다.
className 처럼 정해진 상황을 모두 컨트롤 할 수 있는 값이 아닙니다.
기본만 보여줘도 될듯합니다.

2022-08-13 09:30 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.tsx
> +  classname,
실제 컴포넌트에 클래스명을 정의하는 경우와 동일해야 사용자 입장에서 바로 적용이 편합니다.
실제 컴포넌트의 클래스명을 정의하는 속성명은 `className` 입니다.

2022-08-13 12:29 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.tsx
> +  classname,
Standard를 따르라는 말인것이죠?? ❓

2022-08-13 12:33 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.scss
> +img {
[수정하였습니다.](https://github.com/TheNewestWorld/groove-front/pull/15/commits/1a949b96243b3e2c30221bfa735c33bfbaa7c38d#diff-2efe8dacc570e3a8aae1fd3214788ce309cc44934deb6e6f1104ad7054986202R4-R8)

2022-08-13 21:18 UTC, wlsdhr0831 approved these changes
이거 2개만 수정되면 될 것 같네요~
수정 후 머지 진행해주세요 수고하셨습니다 👍🏻👍🏻👍🏻

2022-08-13 21:18 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.stories.scss
> +}
이 파일 삭제는 안하시나요~?

2022-08-13 21:18 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.tsx
> +        "circle-image",
img 태그에는 클래스 명이 없어도 되지 않나요..?
css 상으로 img 태그에 속성을 추가 한 것 같은데...
만약 사용하실 예정이라면 19줄에 사용한 클래스명과는 다르게 명명하셔야하고
css 파일 내에서도 img 태그가 아니라 사용하는 클래스명으로 속성을 적용하는게 좋을 것 같습니다~

2022-08-13 21:19 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.tsx
> +        "circle-image",
클래스명을 사용하지 않는쪽으로 수정 시 classnames도 같이 사용하지 않는 방향으로 수정하셔야 합니다~

2022-08-14 07:39 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.tsx
> +        "circle-image",
후자로 수정하였습니다~

2022-08-14 08:04 UTC, wlsdhr0831 commented on src/components/CircleImage/CircleImage.tsx
>      <div className="circle-image">
@Ho2eny 이건 반영되지 않은 것 같은데 resolved 되어 있네요~??
img 태그가 아니라 그걸 감싸는 전체 컴포넌트에 props로 받은 className이 적용되어야 합니다!
그래야 전체 적인 위치 css 적용이 가능해요!

2022-08-14 08:12 UTC, Ho2eny commented on src/components/CircleImage/CircleImage.tsx
>      <div className="circle-image">
아! 이해했습니다! 반영했습니다~ 👍

2022-08-14 08:20 UTC, merged